### ISSUE TITLE
[ERROR]  Could not connect to database.

### ISSUE THREAD

**Issue by JPRuehmann** [geigi/cozy#228]
### Bug/Feature description
Can´t start cozy

### Steps to reproduce
sudo XDG_DATA_DIRS=/opt/cozy/share:/usr/share:/usr/local/share PYTHONPATH=/opt/cozy/lib/python3/dist-packages /opt/cozy/bin/com.github.geigi.cozy

### System Information
['/opt/cozy/bin/com.github.geigi.cozy']
- Operating System: 
19:28:41 [MainThread  ] [main      ] [INFO ]  ('ubuntu', '18.04', 'Bionic Beaver')
- Version of cozy: 
19:28:41 [MainThread  ] [main      ] [INFO ]  Starting up cozy 0.6.10
19:28:41 [MainThread  ] [db        ] [ERROR]  Could not connect to database. 
19:28:41 [MainThread  ] [db        ] [ERROR]  connect() got an unexpected keyword argument 'reuse_if_open'
Traceback (most recent call last):
  File "/opt/cozy/lib/python3/dist-packages/cozy/control/db_updater.py", line 108, in update_db
    next(c for c in db.get_columns("settings") if c.name == "version")
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/cozy/bin/com.github.geigi.cozy", line 74, in do_startup
    init_db()
  File "/opt/cozy/lib/python3/dist-packages/cozy/control/db.py", line 36, in init_db
    update_db()
  File "/opt/cozy/lib/python3/dist-packages/cozy/control/db_updater.py", line 116, in update_db
    __update_db_1(db)
  File "/opt/cozy/lib/python3/dist-packages/cozy/control/db_updater.py", line 22, in __update_db_1
    migrator.add_column('track', 'crc32', crc32),
  File "/usr/lib/python3/dist-packages/playhouse/migrate.py", line 717, in migrate
    operation.run()
  File "/usr/lib/python3/dist-packages/playhouse/migrate.py", line 144, in run
    getattr(self.migrator, self.method)(*self.args, **kwargs))
  File "/usr/lib/python3/dist-packages/playhouse/migrate.py", line 138, in _handle_result
    self._handle_result(item)
  File "/usr/lib/python3/dist-packages/playhouse/migrate.py", line 135, in _handle_result
    result.run()
  File "/usr/lib/python3/dist-packages/playhouse/migrate.py", line 144, in run
    getattr(self.migrator, self.method)(*self.args, **kwargs))
  File "/usr/lib/python3/dist-packages/playhouse/migrate.py", line 135, in _handle_result
    result.run()
  File "/usr/lib/python3/dist-packages/playhouse/migrate.py", line 144, in run
    getattr(self.migrator, self.method)(*self.args, **kwargs))
  File "/usr/lib/python3/dist-packages/playhouse/migrate.py", line 152, in inner
    return fn(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/playhouse/migrate.py", line 554, in _update_column
    (column_to_update, table))
ValueError: Column "version" does not exist on "settings"

- Installation source: 
git clone https://github.com/geigi/cozy.git

**Comment by geigi** [comment]
This happens when the database is corrupted. Sadly there is currently no other way than deleting the db and start over. I’ll have to investigate this issue.

In the meantime to get you up and running again:
`rm -r ~/.local/share/cozy`

**Comment by JPRuehmann** [comment]
there is no Database.
The Folder is empty.

**Comment by geigi** [comment]
This might be because you try to run cozy with sudo. This is not supported and should not be done as cozy doesn't require root permissions. Could you try running cozy without sudo?

**Comment by geigi** [comment]
It was indeed a bug, I fixed it in the latest version. Thanks for reporting :)

**Comment by JPRuehmann** [comment]
Updated it
still wont run

com.github.geigi.cozy                                                                                                                                           
Traceback (most recent call last):
  File "/usr/local/bin/com.github.geigi.cozy", line 28, in <module>
    from cozy.ui import CozyUI
ModuleNotFoundError: No module named 'cozy'

/opt/cozy/bin/com.github.geigi.cozy                                                                                                                             
Traceback (most recent call last):
  File "/opt/cozy/bin/com.github.geigi.cozy", line 35, in <module>
    from cozy.ui.main_view import CozyUI
ModuleNotFoundError: No module named 'cozy'

which com.github.geigi.cozy                                                                                                                                   
/usr/local/bin/com.github.geigi.cozy

**Comment by geigi** [comment]
This looks like an issue with your pythonpath variable as cozy is unable to find its components. Make sure your pythonpath contains the path to the installed cozy python components.

**Comment by JPRuehmann** [comment]
I don´t have such a Variable. how can I Set it?
How do I find out where to point it?

**Comment by geigi** [comment]
Im sorry you have to write it in all caps like this: PYTHONPATH

Have a look at the build and run local build section in the readme. The desired installation directory needs to be in the python path.

Although I highly recommend you to use the flatpak release of cozy instead of installing it manually as flatpak does everything for you and it just works out of the box on almost every Linux distribution. Have a look here: https://www.flathub.org/apps/details/com.github.geigi.cozy

**Comment by JPRuehmann** [comment]
Ok
XDG_DATA_DIRS=/opt/cozy/share:/usr/share PYTHONPATH=/opt/cozy/lib/python3/dist-packages /opt/cozy/bin/com.github.geigi.cozy
does it.

Thanks,
